# Generated by Django 4.2.8 on 2024-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="opinion",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
