# Generated by Django 4.2.8 on 2024-01-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_opinion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opinion_text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveField(
            model_name="blog",
            name="opinion",
        ),
        migrations.AddField(
            model_name="blog",
            name="opiniones",
            field=models.ManyToManyField(blank=True, to="blog.opinion"),
        ),
    ]
