# Generated by Django 4.2.8 on 2024-01-04 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_opinion_remove_blog_opinion_blog_opiniones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 16, 28, 13, 622546, tzinfo=datetime.timezone.utc)),
        ),
    ]
