# Generated by Django 4.2.8 on 2024-01-04 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_opinion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 16, 30, 36, 965982, tzinfo=datetime.timezone.utc)),
        ),
    ]
