# Generated by Django 4.2.8 on 2024-01-05 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_opinion_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 15, 18, 14, 93975, tzinfo=datetime.timezone.utc)),
        ),
    ]
