# Generated by Django 4.2.8 on 2024-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portafolio_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created"],
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="descripcion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="imagen",
            field=models.ImageField(upload_to="projects", verbose_name="Imagen"),
        ),
    ]
