# Generated by Django 4.2.8 on 2024-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                (
                    "imagen",
                    models.ImageField(upload_to="skills", verbose_name="Imagen"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "conocimiento",
                "verbose_name_plural": "conocimientos",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterModelOptions(
            name="about",
            options={
                "ordering": ["-created"],
                "verbose_name": "formación",
                "verbose_name_plural": "formaciones",
            },
        ),
        migrations.AddField(
            model_name="about",
            name="degree_title",
            field=models.CharField(
                default=None, max_length=300, verbose_name="Título obtenido"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="about",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]
