# Generated by Django 4.2.8 on 2024-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_skills_alter_about_options_about_degree_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['created'], 'verbose_name': 'conocimiento', 'verbose_name_plural': 'conocimientos'},
        ),
        migrations.AddField(
            model_name='about',
            name='photo_perfil',
            field=models.ImageField(default=None, upload_to='poto_perfil', verbose_name='Foto de perfil'),
            preserve_default=False,
        ),
    ]
