# Generated by Django 4.2.8 on 2024-01-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_skills_options_about_photo_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='photo_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='poto_perfil', verbose_name='Foto de perfil'),
        ),
    ]
